### ISSUE TITLE
Differentiate destructive and 'Thanks' colors.

### ISSUE THREAD

**Issue by dcndr** [SubjectiveLabs/SubjectiveAssembly#39]
<img width="441" alt="image" src="https://github.com/SubjectiveLabs/SubjectiveAssembly/assets/56007854/f2e657a1-8af1-46bb-942f-bcc8886908d3">

Make destructive not fully red, but less pink.

**Comment by circles-png** [comment]
pick a colour from https://tailwindcss.com/docs/customizing-colors

**Comment by circles-png** [comment]
colours of these elements are `/frontend/src/App.tsx` lines 210, 242 and 249
