### ISSUE TITLE
Add belltime disabling.

### ISSUE THREAD

**Issue by dcndr** [SubjectiveLabs/SubjectiveAssembly#56]
nil: take user selection
true: force disabled
false: force undisabled

Maybe use a three state toggle with middle being nil?

**Comment by circles-png** [comment]
no make an enum
give swift type

**Comment by dcndr** [comment]
advantages?

**Comment by circles-png** [comment]
readability counts

**Comment by circles-png** [comment]
> undisabled
??

```rust
enum BellState {
    User,
    Enabled,
    Disabled,
}
```

**Comment by dcndr** [comment]
ffr made it two state (enabled: Bool)
